### ISSUE TITLE
Halt server start until EULA is accepted

### ISSUE THREAD

**Issue by jellz** [jellz/minecraft-server#16]
Mojang requires all server owners to agree to the [EULA](https://account.mojang.com/documents/minecraft_eula) when operating a server. This project should stop the server from starting until the EULA is accepted. Spigot creates a text file and doesn't operate until the boolean is changed from false to true in the file.

**Comment by ckiee** [comment]
well all of this is your code so you don't need to make them agree to their eula?

**Comment by robertt** [comment]
it's still a minecraft server

**Comment by ThatTonybo** [comment]
Where's the server start from? It should be a rather simple function to implement:
- check if the file exists.
- if it exists:
    - open it and check for true/false, and start/stop depending on it.
- if it doesn't:
    - create the file and stop.

All it'd need is `fs` and a couple lines, nothing crazy.

**Comment by youngchief-btw** [comment]
I agree about not allowing the server to start until they accept.
