### ISSUE TITLE
VOID ?

### ISSUE THREAD

**Issue by TapsHTS** [jellz/minecraft-server#21]
When i join the server, I'm in the void ? That's normal ?
![image](https://user-images.githubusercontent.com/61658427/105970069-3de2ec80-6089-11eb-8f86-1762ea581e36.png)

**Comment by mbouli** [comment]
yea this wasnt ever finished

**Comment by jellz** [comment]
I never got around to adding chunk loading/generation to the server, so yes that is intended.
