### ISSUE TITLE
Are you still here jellz?

### ISSUE THREAD

**Issue by KaffinPX** [jellz/minecraft-server#22]
I think i can help to develop but i must ask are you online first?

**Comment by IlanLuci** [comment]
They do not actively maintain the project anymore. I think it is still a really cool idea and would love to see it done.

**Comment by KaffinPX** [comment]
If i create a pull-request he will merge it?

**Comment by IlanLuci** [comment]
I would assume so but am not sure. I will dm him on discord.

**Comment by IlanLuci** [comment]
He says "I can probably merge PRs"

**Comment by jellz** [comment]
Hey. I don't actively work on this project anymore but I can look into merging pull requests. I'd recommend forking the project and maintaining your own version, but I can merge changes to this if you want.

**Comment by IlanLuci** [comment]
I also would like to work on this. I have a descent amount of programming experience but not much knowledge on how chunk loading works in mc. I will do some research and learn what I can. @KaffinPX Let me know if I can help in any way on developing this.

**Comment by oblx** [comment]
Hi, it looks like there is an other nodejs mc server with a fair amount of contributors (including @KaffinPX, what a nice surprise :)). Maybe it's better to team up and focus on a single repo ?

**Comment by KaffinPX** [comment]
Yes, we can continue to Flying-squid its a good alternative.

**Comment by KaffinPX** [comment]
> I also would like to work on this. I have a descent amount of programming experience but not much knowledge on how chunk loading works in mc. I will do some research and learn what I can. @KaffinPX Let me know if I can help in any way on developing this.

We can work on Flying-squid
